/*************************************************************
/IMAGER_v2.0 (2016)
/main.cpp
/Application entry point.
/Autogenerated file. Not to be modified.
**************************************************************/
#include "mainwindow.h"
#include <QApplication>

int activeFlag;
QString exposure;
QString xBin;
QString yBin;

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    MainWindow w;
    w.setWindowState(w.windowState() ^ Qt::WindowActive);
    w.show();

    return a.exec();
}
